### ISSUE TITLE
Repos are duplicated in the list

### ISSUE THREAD

**Issue by patdolem** [rauhryan/huboard#589]
Some repos are duplicated in the list used to open the dashboards (see screenshot):
![duplicated repos](https://cloud.githubusercontent.com/assets/5685914/9741468/6f38643e-560f-11e5-9791-60ea32f5b468.png)

**Comment by discorick** [comment]
Hi @patdolem , have you recently upgraded you GitHub Enterprise installation ? The GH API team made some changes, the newest build of HuBoard Enterprise should fix this.

**Comment by patdolem** [comment]
@discorick Let me check if the upgrade happened.

**Comment by patdolem** [comment]
@discorick We are behind at least one release. We'll upgrade this week-end and let you know if we are still having this issue.

**Comment by discorick** [comment]
@patdolem sounds good! We will try to have a bleeding edge enterprise release for this weekend as well.

**Comment by patdolem** [comment]
This was fixed in the last release.

**Comment by rauhryan** [comment]
:tada: :hand:
